
LK_PREFIXES='###PREFIXES###'
LK_SUFFIXES='###SUFFIXES###'

PREFIX='prefix'
STEM='stem'
SUFFIX='suffix'
AFFIX='affix'
COMPLEX_PREFIX='complex_prefix'
COMPLEX_SUFFIX='complex_suffix'
COMPLEX_AFFIX='complex_affix'
TYPE_COUNT='type_count'
TOKEN_COUNT='token_count'
AVERAGE_COUNT_PER_WORD='average_count_per_word'
AVERAGE_LENGTH='average_length'
COUNT='count'
FREQUENCY='frequency'
PROBABILITY='probability'
PRECISION='precision'
RECALL='recall'
F1SCORE='f1score'
MORPH_TYPE_COUNT='morph_type_count'
DEGREE_OF_AMBIGUITY='degree_of_ambiguity'
WEIGHTED_DEGREE_OF_AMBIGUITY='weighted_degree_of_ambiguity'
AVERAGE_MORPH_TOKEN_LENGTH='average_morph_token_length'
AVERAGE_MORPH_TYPE_LENGTH='average_morph_type_length'
AVERAGE_NUMBER_OF_MORPHS_PER_WORD='average_number_of_morphs_per_word'
MAX_NUMBER_OF_MORPHS_PER_WORD='max_number_of_morphs_per_word'
SEGMENTATION='segmentation'

ERROR_MESSAGE="An error has occurred! Please check the inputs!"
